[package]
name = "lean-stacks-project"
version = "0.1"
lean_version = "master"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "5193194e954b419e417e3efc84c0e1ebae98e111"}
lean-category-theory = {git = "https://github.com/semorrison/lean-category-theory", rev = "e8dfc711d3de220b46eb45fbafbacdc68344daf0"}
