[package]
name = "lean-stacks-project"
version = "0.1"
lean_version = "master"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "8f680d0818cd3a1e1bf6d9e51c4e07eac08458f5"}
lean-category-theory = {git = "https://github.com/semorrison/lean-category-theory", rev = "69a486e330029265306facfa433fce53108dfa3e"}
