[package]
name = "lean-stacks-project"
version = "0.1"
lean_version = "master"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "f98626c519c3d0e436cddf52772f3669ed9a10c7"}
lean-category-theory = {git = "https://github.com/semorrison/lean-category-theory", rev = "48b380de49c5724fef678ef9c7adc05290f390f3"}
