[package]
name = "lean-stacks-project"
version = "0.1"
lean_version = "nightly-2018-04-02"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "22e671c5ed5fd1b891fb73aa10c9425d1c6cfd3d"}
