[package]
name = "lean-stacks-project"
version = "0.1"
lean_version = "master"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "9b306b2eb7c2bc0e0e7243a7eb43b836d2c867b7"}
lean-category-theory = {git = "https://github.com/semorrison/lean-category-theory", rev = "f1a17a234771426f532e00237365b0d271968e13"}
